LOAD DATA LOCAL INFILE 'player.csv' INTO TABLE Player FIELDS TERMINATED BY ' ';
LOAD DATA LOCAL INFILE 'team.csv' INTO TABLE Team FIELDS TERMINATED BY ' ';
LOAD DATA LOCAL INFILE 'teammember.csv' INTO TABLE TeamMember FIELDS TERMINATED BY ' ';
LOAD DATA LOCAL INFILE 'tournament.csv' INTO TABLE Tournament FIELDS TERMINATED BY ' ';
LOAD DATA LOCAL INFILE 'match.csv' INTO TABLE Matches FIELDS TERMINATED BY ' ';